version: "3.8"

services:
  airflow:
    build:
      context: .
      dockerfile: src/serving/Dockerfile.airflow
    container_name: airflow_local

    user: root

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      PROJECT_ROOT: /app
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
      PYTHONPATH: /app

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/app/src
      - ./data:/app/data
      - ./configs:/app/configs

    working_dir: /app

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create \
        --username airflow \
        --firstname Airflow \
        --lastname Admin \
        --role Admin \
        --email airflow@example.com \
        --password airflow || true &&
      airflow scheduler & airflow webserver
      "
